### PR TITLE
added logo , css gradients

### PR DESCRIPTION
**Pull request by mohittk**
image
#6

### CODE REVIEW

**Review by meinhoonharsh — CHANGES_REQUESTED** [review]
The background gradient is looking good there, but the Search Input and Button, doesn't match with it. It would be great If you can do something for it

**Comment by mohittk** [comment]
> The background gradient is looking good there, but the Search Input and Button, doesn't match with it. It would be great If you can do something for it

Ohh sure! I can do that.

**Comment by mohittk** [comment]
image
is this allright? @meinhoonharsh  or any changes?

**Comment by mohittk** [comment]
@meinhoonharsh bro please respond to the PR. Its been 2 days.

**Comment by meinhoonharsh** [comment]
Sorry for being Inactive 🥲, A Bit busy in some thing, so added `Hacktoberfest-accepted` to this PR

**Comment by mohittk** [comment]
> Sorry for being Inactive 🥲, A Bit busy in some thing, so added `Hacktoberfest-accepted` to this PR

Okay bro! no worries.
So will you merge later on?

**Review by meinhoonharsh — APPROVED** [review]
Again Sorry for being Inactive,  I just resolved the conflicts for the sake of conflicts. It would be great If you can fix them up in a new PR

**Comment by mohittk** [comment]
> Again Sorry for being Inactive, I just resolved the conflicts for the sake of conflicts. It would be great If you can fix them up in a new PR

Ohh sure! I'll see into it.

**Pull request merged**
